### ISSUE TITLE
Run test suite on push and linting on commit

### ISSUE THREAD

**Issue by agarzola** [SoPR/prfaa-donations-backend#5]
I’ve found it very helpful in other projects to enforce test running and ensure that no unlinted code is ever pushed. One thing I’ve never done, but would like to propose regardless, is running the linter on `pre-commit` and the tests on `pre-push`. That way no unlinted code is committed, and no test-breaking code is pushed.

Committing `.git/hooks/pre-push` and `.git/hooks/pre-commit` should suffice, but if you’d rather configure this via `package.json` something like [`pre-push`](https://www.npmjs.com/package/pre-push) and [`pre-commit`](https://www.npmjs.com/package/pre-commit) could be used to help manage these kinds of things.

I’d be happy to submit a PR for this later today if it’s something we’re interested in.

**Comment by nabeards** [comment]
Yes, that would be great. We would benefit from this on the frontend repo as well. :)

**Comment by agarzola** [comment]
Sounds good. PRs incoming shortly.

**Comment by agarzola** [comment]
Closed in #7.
