### ISSUE TITLE
Add user/pass authentication

### ISSUE THREAD

**Issue by nabeards** [SoPR/prfaa-donations-backend#6]
Adding username/password authentication.
This will be used to access the search page.

**Comment by nabeards** [comment]
Plan is to require authentication for all endpoints, will do authorization to certain users for the donationOffer endpoints for search, read, update, delete.

**Comment by MentalPower** [comment]
From an AuthN point of view, we could also lock down the beta endpoint to only be callable from inside the VPC. Where are we keeping the accounts list?

**Comment by nabeards** [comment]
I was thinking just a file on S3, privately-accessible only. Getting that file to Node in the backend server is pretty easy. Do you know of a way to access a file from S3 during the build process for the frontend? I was thinking something like
- read the s3 file
- get the API creds
- add the creds to the web app at startup

**Comment by MentalPower** [comment]
Could we leverage Cognito for the account management piece?
* https://medium.com/@kangzeroo/user-management-with-aws-cognito-1-3-initial-setup-a1a692a657b3
* https://www.npmjs.com/package/react-cognito

**Comment by nabeards** [comment]
Seems like a lot of overhead for just a few accounts. I'm leaning toward the System Manager Parameter Store for EC2.

**Comment by nabeards** [comment]
After further discussion, determined that any API key info we would want to have on the React app will not be secret. Short-term plan is to lock down endpoints so that un-authenticated use is limited, and require user auth for more advanced changes, namely search and major data mods.

**Comment by nabeards** [comment]
I have the auth code ready to push, but search will no longer function when run. What we need is a sign-in prior to loading the search page.

**Comment by nabeards** [comment]
running in production now
